// déclarer que nous faisons du Java ;
plugins{
    id 'java'
}

// indiquer que nos dépendances viennent de Maven Central ;
repositories{
    mavenCentral()
}

// configurer les tests avec JUnit Jupiter.
dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


// configurer Java 21 ;
java{
    toolchain{
        languageVersion = JavaLanguageVersion.of(21)
    }
}


test {
    useJUnitPlatform()
}

